<?php

namespace ContainerWGTbFUd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VrrEvJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vrr_evJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vrr_evJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\UsuarioApiController::confirmarlogin' => ['privates', '.service_locator.Q4iyS3r', 'get_ServiceLocator_Q4iyS3rService', true],
            'App\\Controller\\UsuarioApiController::ingresoP' => ['privates', '.service_locator.Q4iyS3r', 'get_ServiceLocator_Q4iyS3rService', true],
            'App\\Controller\\UsuarioApiController::setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\UsuarioApiController:confirmarlogin' => ['privates', '.service_locator.Q4iyS3r', 'get_ServiceLocator_Q4iyS3rService', true],
            'App\\Controller\\UsuarioApiController:ingresoP' => ['privates', '.service_locator.Q4iyS3r', 'get_ServiceLocator_Q4iyS3rService', true],
            'App\\Controller\\UsuarioApiController:setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\UsuarioApiController::confirmarlogin' => '?',
            'App\\Controller\\UsuarioApiController::ingresoP' => '?',
            'App\\Controller\\UsuarioApiController::setViewHandler' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\UsuarioApiController:confirmarlogin' => '?',
            'App\\Controller\\UsuarioApiController:ingresoP' => '?',
            'App\\Controller\\UsuarioApiController:setViewHandler' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
