<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGTbFUd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGTbFUd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWGTbFUd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWGTbFUd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWGTbFUd\App_KernelDevDebugContainer([
    'container.build_hash' => 'WGTbFUd',
    'container.build_id' => 'c1f07b10',
    'container.build_time' => 1612280221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGTbFUd');
